name: Build and Deploy Image and Documentation

on:
  push:
    tags: [ "v*" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write


    steps:
    - uses: actions/checkout@v4




    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and Deploy Docker Image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: ./src
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}




    - name: Build Documentation
      run: |
        docker run --rm -v "${{ github.workspace }}/docs":/docs ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} make html
        cd ./docs/_build/html
        zip -r ${{ github.workspace }}/documentation-${{ github.ref_name }}.zip .


    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html




    - name: Recover Release Data
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: bump-version.yml
        workflow_conclusion: success
        name: release-${{ github.ref_name }}
        path: release-note.md 
        search_artifacts: true

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: "release-note.md"
        tag_name: ${{ github.ref_name }}
        files: |
            release-note.md
            documentation-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
